### ISSUE TITLE
Oauth2 Authentification

### ISSUE THREAD

**Issue by PhilippeDeSousa** [epicare2021/API#29]
- [x] Token

- [x] RefreshToken

- [x] Temporary tokens

**Comment by KillianG** [comment]
Pourquoi tu veux faire du Oauth2 ?

**Comment by PhilippeDeSousa** [comment]
Notre propre OAuth2 pour sécuriser l'authentification

**Comment by PhilippeDeSousa** [comment]
> Pourquoi tu veux faire du Oauth2 ?

Notre propre OAuth2 pour sécuriser l'authentification
